-include Makefile.local

NAME           := Desgrana
VERSION        := $(shell cat VERSION)
DATE           := $(shell date +"%B %-d %Y")
GITHUB_REPO    := rdalverny/desgrana
GITHUB_BASE    := https://github.com/$(GITHUB_REPO)/releases/download
BUILD          := var/build
DIST           := dist

SPM_NATIVE_DIR  := desgrana/.build/release
CLI_BUILD       := $(BUILD)/desgrana

BUILDINFO       := desgrana/Sources/Core/BuildInfo.swift
GIT_SHA         := $(shell git rev-parse HEAD 2>/dev/null || echo 0000000000000000000000000000000000000000)
GIT_DESCRIBE    := $(shell git describe --tags --always --dirty 2>/dev/null || echo unknown)
GIT_DIRTY       := $(shell git diff --quiet 2>/dev/null && git diff --cached --quiet 2>/dev/null && echo false || echo true)
BUILD_DATE      := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
SWIFT_VERSION   := $(shell swift --version 2>/dev/null | head -1 | tr -d '"\\')
TOOLCHAIN       := $(shell swift --version 2>/dev/null | grep -i target | head -1 | sed 's/^ *//' | tr -d '"\\')


include make/macos.mk
include make/linux.mk
include make/release.mk

# Lock the default goal so it can't shift when fragments are reordered.
.DEFAULT_GOAL := buildinfo

.PHONY: buildinfo cli test test-unit test-generate tag patch minor \
        lint lint-fix format format-check clean fmtdoc web

# ── Build ─────────────────────────────────────────────────────────

# Generate BuildInfo.swift (version + commit) when its contents change. Gitignored
# so it never dirties the working tree (see `tag`). Required by every Swift build.
buildinfo:
	@mkdir -p $(dir $(BUILDINFO)); \
	 tmp=$$(mktemp); \
	 { echo "// Generated by 'make buildinfo' — do not edit, gitignored."; \
	   echo "public enum BuildInfo {"; \
	   echo "    public static let version = \"$(VERSION)\""; \
	   echo "    public static let gitSHA = \"$(GIT_SHA)\""; \
	   echo "    public static let gitDescribe = \"$(GIT_DESCRIBE)\""; \
	   echo "    public static let gitDirty = $(GIT_DIRTY)"; \
	   echo "    public static let buildDate = \"$(BUILD_DATE)\""; \
	   echo "    public static let swiftVersion = \"$(SWIFT_VERSION)\""; \
	   echo "    public static let toolchain = \"$(TOOLCHAIN)\""; \
	   echo "}"; } > $$tmp; \
	 cmp -s $$tmp $(BUILDINFO) 2>/dev/null || mv $$tmp $(BUILDINFO); \
	 rm -f $$tmp

cli: buildinfo
	cd desgrana && swift build -c release --product desgrana
	mkdir -p $(BUILD)
	cp $(SPM_NATIVE_DIR)/desgrana $(CLI_BUILD)
	strip -S $(CLI_BUILD)
	@echo "CLI → $(CLI_BUILD)"

test-unit: buildinfo
	cd desgrana && swift test

test: cli test-unit
	python3 desgrana/Tests/test_split.py $(CLI_BUILD)

test-generate: cli
	python3 desgrana/Tests/test_split.py --generate $(CLI_BUILD)

lint:
	cd desgrana && swiftlint lint --strict

clean:
	rm -rf desgrana/.build \
		var/ \
		dist/ \
		$(APP) \
		$(NAME).zip \
		$(NAME).iconset/ \
		$(NAME).xcassets/

fmtdoc:
	prettier --prose-wrap preserve --print-width 78 --write "**/*.md"

