// SPDX-FileCopyrightText: 2026 Romain d'Alverny
// SPDX-License-Identifier: MIT
import Foundation

// MARK: - DAW session file generators

/// Quotes a string for an RPP token using Reaper's convention: pick a quote
/// character (`"`, `'`, then backtick) that the string does not contain. If it
/// contains all three, fall back to backticks with inner backticks turned into
/// apostrophes. Always quoted, so spaces and empty strings are safe.
func rppQuote(_ s: String) -> String {
    for q in ["\"", "'", "`"] where !s.contains(q) {
        return q + s + q
    }
    return "`" + s.replacingOccurrences(of: "`", with: "'") + "`"
}

/// Generates a Reaper .rpp session file referencing the given WAV files.
/// Note: verify MARKER line syntax against a real .rpp saved by Reaper before shipping —
/// the structure below matches Reaper 6+ community docs but minor version differences exist.
public func generateRPP(
    wavs: [(url: URL, channels: Int)],
    duration: Double,
    sampleRate: Double,
    markers: [(time: Double, name: String)],
    outputDir: URL
) throws -> URL {
    let timestamp = Int(Date().timeIntervalSince1970)

    var lines: [String] = [
        "<REAPER_PROJECT 0.1 \"6.0\" \(timestamp)",
        "  SAMPLERATE \(Int(sampleRate)) 0 0",
        "  TEMPO 120 4 4"
    ]

    func guid() -> String { "{\(UUID().uuidString)}" }

    for wav in wavs {
        let trackName = wav.url.deletingPathExtension().lastPathComponent
        lines += [
            "  <TRACK \(guid())",
            "    NAME \(rppQuote(trackName))",
            "    <ITEM",
            "      POSITION 0",
            String(format: "      LENGTH %.6f", duration),
            "      LOOP 0",
            "      GUID \(guid())",
            "      <SOURCE WAVE",
            "        FILE \(rppQuote(wav.url.path))",
            "      >",
            "    >",
            "  >"
        ]
    }

    for (i, marker) in markers.enumerated() {
        lines.append(String(format:
            "  MARKER %d %.6f %@ 0 0 1",
            i + 1, marker.time, rppQuote(marker.name)))
    }

    lines.append(">")
    let content = lines.joined(separator: "\n") + "\n"
    let rppURL = outputDir.appendingPathComponent(outputDir.lastPathComponent + ".rpp")
    try content.write(to: rppURL, atomically: true, encoding: .utf8)
    return rppURL
}

/// Writes an Audacity labels file (`<name>.txt`, tab-separated start/end/name) next to
/// the session. Point labels use start == end. Returns the written file name, or nil
/// when there are no markers (no file is created in that case).
@discardableResult
public func writeAudacityLabels(
    _ markers: [(time: Double, name: String)],
    outputDir: URL,
    name: String
) throws -> String? {
    guard !markers.isEmpty else { return nil }
    let lines = markers.map { marker -> String in
        // Audacity label track format: start <tab> end <tab> name (point label: start == end).
        String(format: "%.6f\t%.6f\t%@", marker.time, marker.time, marker.name)
    }
    let url = outputDir.appendingPathComponent(name + ".txt")
    try (lines.joined(separator: "\n") + "\n")
        .write(to: url, atomically: true, encoding: .utf8)
    return url.lastPathComponent
}

/// Generates an Audacity LOF ("List Of Files") session referencing the given WAV files.
///
/// LOF is Audacity-specific (not an interchange format). Each `file` line imports as a
/// new track in the same window; all tracks are placed at offset 0 so they line up.
///
/// LOF carries no markers. When markers are present, a sibling Audacity labels file
/// (`<name>.txt`, tab-separated start/end/name) is written next to the LOF so the user
/// can import them via File > Import > Labels. The LOF header points at that file.
///
/// Verified against the LOF format documented in the Audacity manual
/// (commands `file` / `window`, `#` comments, optional `offset`).
public func generateAudacityLOF(
    wavs: [(url: URL, channels: Int)],
    duration: Double,
    sampleRate: Double,
    markers: [(time: Double, name: String)],
    outputDir: URL
) throws -> URL {
    let sessionName = outputDir.lastPathComponent

    // Markers cannot live in a LOF; write a sibling Audacity labels file instead.
    let labelsNote = try writeAudacityLabels(markers, outputDir: outputDir, name: sessionName)

    var lines: [String] = ["# Audacity session generated by desgrana"]
    if let note = labelsNote {
        lines.append("# Markers in \"\(note)\" - import via File > Import > Labels")
    }
    // Reference WAVs by absolute path; all aligned at offset 0 (parallel tracks).
    for wav in wavs {
        lines.append("file \"\(wav.url.path)\"")
    }

    let content = lines.joined(separator: "\n") + "\n"
    let lofURL = outputDir.appendingPathComponent(sessionName + ".lof")
    try content.write(to: lofURL, atomically: true, encoding: .utf8)
    return lofURL
}

/// Generates a minimal Ardour session file (.ardour) referencing the given WAV files.
/// XML format verified against session version 3002 (Ardour 6/7).
/// Test with actual Ardour before shipping.
public func generateArdourSession(
    wavs: [(url: URL, channels: Int)],
    duration: Double,
    sampleRate: Double,
    markers: [(time: Double, name: String)],
    outputDir: URL
) throws -> URL {
    struct Track {
        let wav: URL
        let name: String
        let frames: Int64
        let channels: Int
        let sourceID: Int
        let regionID: Int
        let playlistID: Int
        let routeID: Int
        let diskstreamID: Int
    }

    var idCounter = 1
    func nextID() -> Int { defer { idCounter += 1 }; return idCounter }

    let sessionFrames = Int64(duration * sampleRate)

    let tracks: [Track] = wavs.map { wav in
        Track(
            wav: wav.url,
            name: wav.url.deletingPathExtension().lastPathComponent,
            frames: sessionFrames,
            channels: wav.channels,
            sourceID: nextID(), regionID: nextID(),
            playlistID: nextID(), routeID: nextID(), diskstreamID: nextID()
        )
    }

    let sessionEnd   = tracks.map(\.frames).max() ?? 0
    let sessionLocID = nextID()
    let markerIDs    = markers.map { _ in nextID() }
    let sessionName  = outputDir.lastPathComponent

    func x(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
    }

    func tag(_ name: String, _ attrs: [(String, String)], selfClosing: Bool = true) -> String {
        let a = attrs.map { "\($0.0)=\"\($0.1)\"" }.joined(separator: " ")
        return selfClosing ? "<\(name) \(a)/>" : "<\(name) \(a)>"
    }

    var lines: [String] = [
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
        tag("Session", [
            ("version",       "3002"),
            ("name",          x(sessionName)),
            ("sample-rate",   "\(Int(sampleRate))"),
            ("end-is-free",   "1"),
            ("id-counter",    "\(idCounter)"),
            ("name-counter",  "1"),
            ("event-counter", "0"),
            ("vca-counter",   "1")
        ], selfClosing: false) + ">",
        "  <Sources>"
    ]

    for t in tracks {
        lines.append("  " + tag("Source", [
            ("name",    x(t.wav.lastPathComponent)),
            ("type",    "audio"),
            ("flags",   ""),
            ("id",      "\(t.sourceID)"),
            ("channel", "0"),
            ("origin",  "./\(x(t.wav.lastPathComponent))"),
            ("gain",    "1")
        ]))
    }

    lines += ["  </Sources>", "  <Regions/>", "  <Playlists>"]

    for t in tracks {
        lines += [
            "  " + tag("Playlist", [
                ("id",              "\(t.playlistID)"),
                ("name",            "\(x(t.name)).1"),
                ("type",            "audio"),
                ("orig-track-id",   "\(t.routeID)"),
                ("shared-with-ids", ""),
                ("frozen",          "0"),
                ("combine-ops",     "0")
            ], selfClosing: false) + ">",
            "    " + tag("Region", [
                ("name",                  x(t.name)),
                ("muted",                 "0"),
                ("opaque",                "1"),
                ("locked",                "0"),
                ("video-locked",          "0"),
                ("automatic",             "0"),
                ("whole-file",            "1"),
                ("import",                "0"),
                ("external",              "1"),
                ("sync-marked",           "0"),
                ("left-of-split",         "0"),
                ("right-of-split",        "0"),
                ("hidden",                "0"),
                ("position-locked",       "0"),
                ("valid-transients",      "0"),
                ("start",                 "0"),
                ("length",                "\(t.frames)"),
                ("position",              "0"),
                ("beat",                  "0"),
                ("sync-position",         "0"),
                ("ancestral-start",       "0"),
                ("ancestral-length",      "\(t.frames)"),
                ("stretch",               "1"),
                ("shift",                 "1"),
                ("positional-lock-style", "AudioTime"),
                ("layering-index",        "0"),
                ("envelope-active",       "0"),
                ("default-fade-in",       "0"),
                ("default-fade-out",      "0"),
                ("fade-in-active",        "1"),
                ("fade-out-active",       "1"),
                ("scale-amplitude",       "1"),
                ("id",                    "\(t.regionID)"),
                ("type",                  "audio"),
                ("first-edit",            "nothing"),
                ("source-0",              "\(t.sourceID)"),
                ("master-source-0",       "\(t.sourceID)"),
                ("channels",              "\(t.channels)")
            ]),
            "  </Playlist>"
        ]
    }

    lines += ["  </Playlists>", "  <UnusedPlaylists/>", "  <Routes>"]

    for t in tracks {
        lines += [
            "  " + tag("Route", [
                ("id",                  "\(t.routeID)"),
                ("name",                x(t.name)),
                ("default-type",        "audio"),
                ("strict-io",           "1"),
                ("active",              "1"),
                ("denormal-protection", "0"),
                ("meter-point",         "MeterPostFader"),
                ("meter-type",          "MeterPeak"),
                ("saved-meter-point",   "MeterPostFader"),
                ("mode",                "Normal")
            ], selfClosing: false) + ">",
            "    " + tag("Diskstream", [
                ("flags",              "Recordable"),
                ("playlist",           "\(x(t.name)).1"),
                ("name",               x(t.name)),
                ("id",                 "\(t.diskstreamID)"),
                ("speed",              "1"),
                ("capture-alignment",  "Automatic"),
                ("record-safe",        "0"),
                ("channels",           "\(t.channels)")
            ]),
            "  </Route>"
        ]
    }

    lines += ["  </Routes>", "  <Locations>"]
    lines.append("  " + tag("Location", [
        ("id",                  "\(sessionLocID)"),
        ("name",                "session"),
        ("start",               "0"),
        ("end",                 "\(sessionEnd)"),
        ("flags",               "IsSessionRange"),
        ("locked",              "0"),
        ("position-lock-style", "AudioTime")
    ]))
    for (i, marker) in markers.enumerated() {
        let sample = Int64(marker.time * sampleRate)
        lines.append("  " + tag("Location", [
            ("id",                  "\(markerIDs[i])"),
            ("name",                x(marker.name)),
            ("start",               "\(sample)"),
            ("end",                 "\(sample)"),
            ("flags",               "IsMark"),
            ("locked",              "0"),
            ("position-lock-style", "AudioTime")
        ]))
    }
    lines += ["  </Locations>", "</Session>"]

    let content = lines.joined(separator: "\n") + "\n"
    let ardourURL = outputDir.appendingPathComponent(sessionName + ".ardour")
    try content.write(to: ardourURL, atomically: true, encoding: .utf8)
    return ardourURL
}
